[package]
name = "cloudrender"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
cgmath = "0.18.0"
glow = { version = "0.16.0", default-features = false }
rand = "0.9.0"
sdl3 = { version = "0", features = [] }
